### PR TITLE
Nearest Neighbor Filtering, to sharpen pixels.

### PR DESCRIPTION
**Pull request by Nopey**
### Added a checkbox next to Alpha that enables nearest neighbor, sharpening all the pixels.

(Its labelled "Sharp Pixels", and is enabled by default)
The nearest neighbor is just using THREE's filters:
`whatevertexture.magFilter=THREE.NearestFilter`
### I Also changed #resourcepacks and #templates to elements in a table rather than absolutely positioned divs, because tables make the positioning automatic.

(You can move around the elements using margins and paddings though, if you really liked that gap you had before.)

### CODE REVIEW

**Comment by Nopey** [comment]
[Screenshot](http://nopey.net46.net/res/modelviewer.png)

**Comment by F0x06** [comment]
Hi, 

Good work!, thanks :)

**Comment by F0x06** [comment]
Also added you to the contributors section of code headers :)

**Comment by Nopey** [comment]
thx

**Pull request merged**
